# Generated by Django 4.1.4 on 2023-01-10 06:20

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, unique=True, verbose_name='部门名称')),
                ('department_description', models.CharField(max_length=1000, null=True, verbose_name='部门描述')),
                ('department_createtime', models.CharField(max_length=100, null=True, verbose_name='创建时间')),
                ('department_updatetime', models.CharField(max_length=100, null=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistoryManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_username', models.CharField(max_length=20, null=True, verbose_name='登录用户名')),
                ('login_password', models.CharField(max_length=1000, null=True, verbose_name='登录密码')),
                ('login_client_ip', models.CharField(blank=True, max_length=1000, null=True, verbose_name='登录IP')),
                ('login_flag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='登录成功')),
                ('login_time', models.CharField(max_length=100, null=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录历史信息',
                'verbose_name_plural': '登录历史信息',
            },
        ),
        migrations.CreateModel(
            name='UserNameManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_sex', models.CharField(max_length=20, null=True, verbose_name='性别')),
                ('user_work', models.CharField(blank=True, max_length=1000, null=True, verbose_name='岗位')),
                ('user_email', models.EmailField(blank=True, max_length=1000, null=True, verbose_name='邮箱')),
                ('user_desc', models.CharField(max_length=1000, null=True, verbose_name='备注')),
                ('user_createtime', models.CharField(max_length=100, null=True, verbose_name='创建时间')),
                ('user_updatetime', models.CharField(max_length=100, null=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DepartmentManage', to='system.departmentmanage', verbose_name='所属部门')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
